export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_USER = 'FETCH_USER';
export const USER_SELECTED = 'USER_SELECTED';
export const DEPOSIT_ACCOUNT = 'DEPOSIT_ACCOUNT';
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const EDIT_USER = 'EDIT_USER';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const ERROR_PASSWORD='ERROR_PASSWORD';

export const FETCH_TRIP = 'FETCH_TRIP';
export const ADD_TRIP = 'ADD_TRIP';
export const EXTEND_TRIP = 'EXTEND_TRIP';
export const COMPLETE_TRIP = 'COMPLETE_TRIP';
export const TRIP_ERROR = 'TRIP_ERROR';


export const FETCH_TRACK_COORDINATES = 'FETCH_TRACK_COORDINATES';

export const SEND_COMMAND_BU = 'SEND_COMMAND_BU';
export const FETCH_ONBOARD_DEVICE = 'FETCH_ONBOARD_DEVICE';
export const FETCH_ONBOARD_DEVICE_COMBO = 'FETCH_ONBOARD_DEVICE_COMBO';
export const ADD_ONBOARD_DEVICE = 'ADD_ONBOARD_DEVICE';
export const EDIT_ONBOARD_DEVICE = 'EDIT_ONBOARD_DEVICE';
export const UPDATE_ONBOARD_DEVICE = 'UPDATE_ONBOARD_DEVICE';
export const ONBOARD_DEVICE_ERROR = 'ONBOARD_DEVICE_ERROR';


export const FETCH_COMMAND = 'FETCH_COMMAND';
export const ADD_CHARIOT_COMMAND = 'ADD_CHARIOT_COMMAND';

export const FETCH_CHARIOT_COMMAND = 'FETCH_CHARIOT_COMMAND';
export const FETCH_CHARIOT_EVENT = 'FETCH_CHARIOT_EVENT';

export const FETCH_STATION_MET_EVENT = 'FETCH_STATION_MET_EVENT';

export const FETCH_STATION_MET = 'FETCH_STATION_MET';
export const FETCH_SELECT_STATION_MET = 'FETCH_SELECT_STATION_MET';
export const ADD_STATION_MET = 'ADD_STATION_MET';
export const EDIT_STATION_MET = 'EDIT_STATION_MET';
export const UPDATE_STATION_MET = 'UPDATE_STATION_MET';
export const STATION_MET_ERROR = 'STATION_MET_ERROR';


export const FETCH_MET_COORDINATES = 'FETCH_MET_COORDINATES';

export const FETCH_CHARIOT_RENT_INFO = 'FETCH_CHARIOT_RENT_INFO';

export const FETCH_TARIF = 'FETCH_TARIF';
export const ADD_TARIF = 'ADD_TARIF';
export const FETCH_TARIF_TYPE = 'FETCH_TARIF_TYPE';
export const FETCH_MET_TYPE = 'FETCH_MET_TYPE';
export const TARIF_ERROR = 'TARIF_ERROR';

export const EDIT_TARIF = 'EDIT_TARIF';
export const UPDATE_TARIF = 'UPDATE_TARIF';
export const DELETE_TARIF = 'DELETE_TARIF';

export const FETCH_DEVICE_MODE = 'FETCH_DEVICE_MODE';

export const FETCH_TRANSACTION_TYPE = 'FETCH_TRANSACTION_TYPE';
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';



export const FETCH_MET = 'FETCH_MET';
export const FETCH_MET_COMBO = 'FETCH_MET_COMBO';
export const ADD_MET = 'ADD_MET';
export const EDIT_MET = 'EDIT_MET';
export const UPDATE_MET = 'UPDATE_MET';
export const MET_ERROR = 'MET_ERROR';


export const FETCH_CHARIOT = 'FETCH_CHARIOT';
export const ADD_CHARIOT = 'ADD_CHARIOT';
export const EDIT_CHARIOT = 'EDIT_CHARIOT';
export const UPDATE_CHARIOT = 'UPDATE_CHARIOT';
export const CHARIOT_ERROR = 'CHARIOT_ERROR';


export const FETCH_SLOT = 'FETCH_SLOT';
export const ADD_SLOT = 'ADD_SLOT';
export const EDIT_SLOT = 'EDIT_SLOT';
export const UPDATE_SLOT = 'UPDATE_SLOT';
export const SLOT_ERROR = 'SLOT_ERROR';


export const FETCH_USER_PERMISSION = 'FETCH_USER_PERMISSION';
export const ADD_USER_PERMISSION = 'ADD_USER_PERMISSION';
export const DELETE_USER_PERMISSION = 'DELETE_USER_PERMISSION';
export const USER_PERMISSION_ERROR = 'USER_PERMISSION_ERROR';


export const FETCH_PERMISSION = 'FETCH_PERMISSION';

export const FETCH_ACTUAL_TARIF = 'FETCH_ACTUAL_TARIF'

export const LANGUAGE = 'LANGUAGE';























